### PR TITLE
Add new parameter origins

### PR DESCRIPTION
**Pull request by fmatoss**
This parameter is used to try multiple origins/hosts for each relative URL.

When you have the same resource with same path, but hosted in multiple domains and the request for the first one fails, it will try the next.

Usage:
```js
nautilus.config({
  origins: ['https://public.cdn.com', 'https://private.cdn.com', 'https://s3.com'],
  paths: { jquery: '/libs/jquery.min.js' }
});
nautilus(['jquery']);
```

It will try to load the script once in the following order:
1. `https://public.cdn.com/libs/jquery.min.js`
2. `https://private.cdn.com/libs/jquery.min.js`
3. `https://s3.com/libs/jquery.min.js`
4. `/libs/jquery.min.js`

### CODE REVIEW

**Comment by raphamorim** [comment]
Hi @fmatoss, thanks for contributing.
I'll review it. In this weekend 👍

**Comment by raphamorim** [comment]
Hi @fmatoss, thanks for contributing. This is a nice idea!

Can you add this info in README?

**Comment by fmatoss** [comment]
Done @raphamorim

**Comment by raphamorim** [comment]
@fmatoss I merged in a another repo: https://github.com/raphamorim/nautilus.js

**Comment by raphamorim** [comment]
I'll release versions from that.
This repo will exists only for nautilus.js globocom's purporse.

This changes make sense, then I'll split this developmente. 'Cause globocom nautilus's usage is a very specific uncommon purpose.

**Pull request closed without merging**
